# Generated by Django 5.0.1 on 2024-01-31 13:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debug01', '0002_mydata_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mydata',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mydata',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='debug01/test_file/'),
        ),
        migrations.AlterField(
            model_name='mydata',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
